service:
  name: ask-japan-pref-guide
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs8.10
  logRetentionInDays: 7
functions:
  mySkill:
    handler: index.handler
    events:
      - alexaSkill
